import { Job, FreelancerProfile, JobCategory, JobStatus } from './types';

// ==========================================
// НАСТРОЙКИ АДМИНИСТРАТОРА И ОПЛАТЫ
// ==========================================

// 1. ID АДМИНИСТРАТОРОВ (Кто видит кнопку "Админ" в меню)
// Узнать свой ID можно в боте: @userinfobot
export const ADMIN_IDS = [
    479936811, 
    123456789, 
    378436952
];

// 2. USERNAME ДЛЯ ОТПРАВКИ ЧЕКОВ
// Сюда перекинет пользователя после нажатия "Я оплатил".
// Вписывайте БЕЗ собачки (@).
export const ADMIN_USERNAME = "yorzhik"; 

// 3. РЕКВИЗИТЫ КАРТЫ (Fallback — если donate.stream недоступен)
export const PAYMENT_DETAILS = {
    card: "2204 3107 7135 1460",
    bank: "Я-Пэй (Yandex)",
    recipient: "Иван И.",
    phone: "+7 (999) 000-00-00"
};

// 4. DONATE.STREAM — ОСНОВНОЙ СПОСОБ ОПЛАТЫ
export const DONATE_STREAM = {
    enabled: true, // false = откат на старую оплату картой
    pageSlug: "hey_freelancer", // ваш слаг на donate.stream
    
    // Генерация ссылки (donate.stream НЕ поддерживает ?message= параметр)
    buildPaymentUrl: (amount: number) => {
        return `https://donate.stream/hey_freelancer?sum=${amount}`;
    },
    
    // Генерация текста для копирования в поле "Сообщение"
    buildMessage: (jobId: string, promoFlags: string) => {
        return `JOB#${jobId}|${promoFlags}`;
    }
};

// ==========================================
// ЦЕНЫ И КОНСТАНТЫ
// ==========================================

export const PROMOTION_PRICES = {
    PIN: 50,        // Цена за закреп (RUB)
    HIGHLIGHT: 50,  // Цена за выделение (RUB)
    URGENT: 50      // Цена за "Срочно" (RUB)
};

// Версия онбординга - при изменении показать онбординг всем пользователям заново
export const ONBOARDING_VERSION = 2;

export const CATEGORY_LABELS: Record<JobCategory, string> = {
  [JobCategory.ALL]: 'Все',
  [JobCategory.DEVELOPMENT]: 'Разработка',
  [JobCategory.DESIGN]: 'Дизайн',
  [JobCategory.MARKETING]: 'Маркетинг',
  [JobCategory.COPYWRITING]: 'Тексты',
  [JobCategory.OTHER]: 'Разное'
};

export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    authorId: 999,
    authorName: 'Alice Corp',
    authorUsername: 'alice_pm',
    title: 'Frontend на React для Дашборда',
    description: 'Нужен Senior React разработчик для создания аналитического дашборда с использованием Recharts. Срок: 2 недели.',
    budget: '150 000 ₽',
    category: JobCategory.DEVELOPMENT,
    status: JobStatus.OPEN,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    isPinned: true,
    isHighlighted: true,
    proposalsCount: 3
  },
  {
    id: '2',
    authorId: 888,
    authorName: 'Bob Studio',
    authorUsername: 'bob_design',
    title: 'Логотип для Кофейни',
    description: 'Требуется минималистичный логотип для новой хипстерской кофейни в центре.',
    budget: '30 000 ₽',
    category: JobCategory.DESIGN,
    status: JobStatus.OPEN,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    isUrgent: true,
    proposalsCount: 0
  }
];

export const MOCK_FREELANCERS: FreelancerProfile[] = [
  {
    userId: 777,
    displayName: 'Иван Петров',
    username: 'ivan_dev',
    bio: 'Full Stack JS разработчик. 5 лет опыта с Node.js и React.',
    skills: ['React', 'Node.js', 'PostgreSQL'],
    portfolioLinks: ['https://github.com/ivan', 'https://ivan.dev']
  },
  {
    userId: 666,
    displayName: 'Мария Сидорова',
    username: 'maria_ui',
    bio: 'UI/UX Дизайнер, специализируюсь на мобильных интерфейсах.',
    skills: ['Figma', 'Tailwind', 'UI Design'],
    portfolioLinks: ['https://behance.net/maria']
  }
];

// Content for the Architecture/Backend Deliverables
export const BACKEND_DOCS = {
  dbSchema: `
-- 1. СХЕМА ТАБЛИЦ (TABLES)

CREATE TABLE IF NOT EXISTS public.users (
    tg_id BIGINT PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT,
    username TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT REFERENCES public.users(tg_id),
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    budget TEXT,
    category TEXT DEFAULT 'OTHER', 
    status TEXT DEFAULT 'PENDING',
    is_active BOOLEAN DEFAULT TRUE,
    is_pinned BOOLEAN DEFAULT FALSE,
    is_highlighted BOOLEAN DEFAULT FALSE,
    is_urgent BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.profiles (
    user_id BIGINT PRIMARY KEY REFERENCES public.users(tg_id),
    bio TEXT,
    skills TEXT[],
    portfolio_links TEXT[],
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.proposals (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    job_id BIGINT REFERENCES public.jobs(id) ON DELETE CASCADE,
    freelancer_id BIGINT REFERENCES public.profiles(user_id),
    cover_letter TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(job_id, freelancer_id)
);

-- ПАРТНЁРСКИЕ КАНАЛЫ (White-label)
CREATE TABLE IF NOT EXISTS public.channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id BIGINT NOT NULL UNIQUE,           -- Telegram channel ID
    channel_username TEXT,                        -- @username канала
    channel_title TEXT,                           -- Название канала из Telegram
    owner_id BIGINT REFERENCES public.users(tg_id),
    categories TEXT[] DEFAULT '{}',               -- Фильтр категорий
    min_budget INT DEFAULT 0,                     -- Мин. бюджет (0 = все)
    is_active BOOLEAN DEFAULT TRUE,
    subscribers_count INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Связь заказов с каналами
CREATE TABLE IF NOT EXISTS public.channel_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT REFERENCES public.jobs(id) ON DELETE CASCADE,
    channel_id BIGINT REFERENCES public.channels(id) ON DELETE CASCADE,
    telegram_message_id BIGINT,                   -- ID поста в канале
    status TEXT DEFAULT 'pending',                -- pending/published/deleted
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(job_id, channel_id)
);

-- Индексы для быстрого поиска
CREATE INDEX IF NOT EXISTS idx_channels_owner ON public.channels(owner_id);
CREATE INDEX IF NOT EXISTS idx_channels_active ON public.channels(is_active);
CREATE INDEX IF NOT EXISTS idx_channel_jobs_job ON public.channel_jobs(job_id);
CREATE INDEX IF NOT EXISTS idx_channel_jobs_channel ON public.channel_jobs(channel_id);

-- 2. ПРАВА ДОСТУПА (RLS POLICIES)
-- Это критически важно! Без этого база не даст сохранить данные.

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access" ON public.users FOR ALL USING (true);

ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access" ON public.jobs FOR ALL USING (true);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access" ON public.profiles FOR ALL USING (true);

ALTER TABLE public.proposals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access" ON public.proposals FOR ALL USING (true);

ALTER TABLE public.channels ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access" ON public.channels FOR ALL USING (true);

ALTER TABLE public.channel_jobs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access" ON public.channel_jobs FOR ALL USING (true);
`,
  edgeFunction: `
// supabase/functions/telegram-bot/index.ts
import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2"

const BOT_TOKEN = Deno.env.get('BOT_TOKEN')!
const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const BOT_USERNAME = 'hey_birazhabot' // Ваш бот

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)

// Helper to send message
const sendMessage = async (chat_id: number | string, text: string, reply_markup?: any) => {
  if (!chat_id) return null
  const res = await fetch(\`https://api.telegram.org/bot\${BOT_TOKEN}/sendMessage\`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ 
      chat_id, 
      text, 
      parse_mode: 'HTML',
      reply_markup 
    })
  })
  return res.json()
}

// Форматирование заказа для публикации в канал
const formatJobPost = (job: any) => {
  const categoryEmoji: Record<string, string> = {
    'DEVELOPMENT': '💻',
    'DESIGN': '🎨',
    'MARKETING': '📈',
    'COPYWRITING': '✍️',
    'OTHER': '📦'
  }
  
  const emoji = categoryEmoji[job.category] || '📦'
  const urgentBadge = job.is_urgent ? '🔥 СРОЧНО\\n\\n' : ''
  
  return \`\${urgentBadge}\${emoji} <b>\${job.title}</b>

\${job.description.slice(0, 500)}\${job.description.length > 500 ? '...' : ''}

💰 <b>Бюджет:</b> \${job.budget || 'Договорная'}

<a href="https://t.me/\${BOT_USERNAME}/app?startapp=job_\${job.id}">👉 Откликнуться</a>\`
}

serve(async (req) => {
  try {
    const payload = await req.json()
    const { type, table, record, old_record } = payload

    // 1. NEW JOB -> NOTIFY ADMINS
    if (table === 'jobs' && type === 'INSERT') {
       const ADMIN_IDS = [${ADMIN_IDS.join(', ')}] 
       const text = \`⚡️ <b>Новый заказ на модерацию!</b>\\n\\nTitle: \${record.title}\\nBudget: \${record.budget}\\n\\n<a href="https://t.me/\${BOT_USERNAME}">Открыть Админку</a>\`
       await Promise.all(ADMIN_IDS.map(id => sendMessage(id, text)))
    }

    // 2. JOB STATUS CHANGE -> NOTIFY AUTHOR + PUBLISH TO CHANNELS
    if (table === 'jobs' && type === 'UPDATE' && record.status !== old_record.status) {
       const statusText = record.status === 'OPEN' ? '✅ Опубликован' : '❌ Закрыт/Отклонен'
       const text = \`🔔 Статус заказа <b>"\${record.title}"</b> изменен:\\n\${statusText}\`
       await sendMessage(record.author_id, text)
       
       // Если заказ одобрен — публикуем в каналы
       if (record.status === 'OPEN') {
         const { data: channelJobs } = await supabase
           .from('channel_jobs')
           .select('*, channels(*)')
           .eq('job_id', record.id)
           .eq('status', 'pending')
         
         if (channelJobs && channelJobs.length > 0) {
           const jobPost = formatJobPost(record)
           
           for (const cj of channelJobs) {
             try {
               const result = await sendMessage(cj.channels.channel_id, jobPost)
               if (result?.ok && result?.result?.message_id) {
                 await supabase
                   .from('channel_jobs')
                   .update({ 
                     status: 'published', 
                     telegram_message_id: result.result.message_id,
                     published_at: new Date().toISOString()
                   })
                   .eq('id', cj.id)
               }
             } catch (e) {
               console.error('Failed to publish to channel:', cj.channels.channel_id, e)
             }
           }
         }
       }
    }

    // 3. NEW PROPOSAL -> NOTIFY JOB AUTHOR
    if (table === 'proposals' && type === 'INSERT') {
       const { data: job } = await supabase.from('jobs').select('title, author_id').eq('id', record.job_id).single()
       if (job) {
         const text = \`👋 <b>Новый отклик на заказ!</b>\\n\\nЗаказ: \${job.title}\\nТекст: "<i>\${record.cover_letter.slice(0, 50)}...</i>"\`
         await sendMessage(job.author_id, text)
       }
    }
    
    // 4. NEW CHANNEL_JOB -> PUBLISH IF JOB IS ALREADY OPEN
    if (table === 'channel_jobs' && type === 'INSERT') {
       const { data: job } = await supabase.from('jobs').select('*').eq('id', record.job_id).single()
       const { data: channel } = await supabase.from('channels').select('*').eq('id', record.channel_id).single()
       
       if (job && channel && job.status === 'OPEN') {
         const jobPost = formatJobPost(job)
         const result = await sendMessage(channel.channel_id, jobPost)
         
         if (result?.ok && result?.result?.message_id) {
           await supabase
             .from('channel_jobs')
             .update({ 
               status: 'published', 
               telegram_message_id: result.result.message_id,
               published_at: new Date().toISOString()
             })
             .eq('id', record.id)
         }
       }
    }

    return new Response("OK", { status: 200 })
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), { status: 500 })
  }
})
`,
  webhookSql: `
-- 3. НАСТРОЙКА УВЕДОМЛЕНИЙ (WEBHOOKS)

-- A. Включаем расширение для HTTP запросов
create extension if not exists pg_net;

-- B. Функция отправки уведомления
create or replace function public.handle_telegram_notification()
returns trigger as $$
declare
  -- ⚠️ ЗАМЕНИТЕ ЭТИ ЗНАЧЕНИЯ НА ВАШИ ИЗ SUPABASE SETTINGS ⚠️
  project_ref text := '[YOUR_PROJECT_REF]'; 
  service_role_key text := '[YOUR_SERVICE_ROLE_KEY]';
  
  -- Ссылка на Edge Function
  url text := 'https://' || project_ref || '.supabase.co/functions/v1/telegram-bot';
begin
  perform net.http_post(
    url := url,
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || service_role_key
    ),
    body := jsonb_build_object(
      'type', TG_OP,
      'table', TG_TABLE_NAME,
      'schema', TG_TABLE_SCHEMA,
      'record', row_to_json(NEW),
      'old_record', CASE WHEN TG_OP = 'INSERT' THEN null ELSE row_to_json(OLD) END
    )
  );
  return NEW;
end;
$$ language plpgsql;

-- C. Создаем триггеры
drop trigger if exists on_job_change on public.jobs;
create trigger on_job_change
after insert or update on public.jobs
for each row execute function public.handle_telegram_notification();

drop trigger if exists on_proposal_new on public.proposals;
create trigger on_proposal_new
after insert on public.proposals
for each row execute function public.handle_telegram_notification();

-- D. Триггер для публикации в каналы
drop trigger if exists on_channel_job_new on public.channel_jobs;
create trigger on_channel_job_new
after insert on public.channel_jobs
for each row execute function public.handle_telegram_notification();
`
};
